name: Test

on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - run: pnpm i --frozen-lockfile
      - run: pnpm test
